- name: Search Hacker News front page
  file: hn.yml 
- name: Search Hacker News front page in French
  file: hnfrench.yml
- name: Search life advice
  file: life.yml
- name: Search sports news
  file: sports.yml
- name: Search arXiv papers on aliens
  file: aliens.yml
- name: Search arXiv papers on BERT
  file: bert.yml
- name: Summarize article
  file: article.yml
- name: Summarize and translate article to French
  file: articlefrench.yml